apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  #namespace: app
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: docker.io/alimadany/order-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081        # <-- matches EXPOSE 8081
          env: # EVERYTHING BELOW THIS LINE IS WILL BE ADJUSTED
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-order-db.db.svc.cluster.local:5432/mydb
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: global-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081                 # <-- probe against 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081                 # <-- probe against 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
