apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-deployment
  ports:
    - port: 80
      targetPort: 8081            # <-- routes to container’s 8081

