apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  #namespace: app
  labels:
    app: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-deployment
          image: docker.io/alimadany/order-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081        # <-- matches EXPOSE 8081
          env: # EVERYTHING BELOW THIS LINE IS WILL BE ADJUSTED
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:     
                  name: global-config
                  key: Postgres_Url_Order
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_PASSWORD
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
