apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  #namespace: app                   # <-- if you’re using namespaces
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service     # match the deployment name
          image: docker.io/alimadany/user-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # EVERYTHING BELOW THIS LINE IS WILL BE ADJUSTED
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-user-db.db.svc.cluster.local:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: global-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
