apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: Y3VzdG9tZXJfZGI=   # base64 for "customer_db"
  MONGO_USER: bW9uZ29fdXNlcg==
  MONGO_PASSWORD: MTIzNA==