apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  SPRING_PROFILES_ACTIVE: k8s
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer_db
  # add any other non-sensitive defaults here
