apiVersion: v1
kind: Service
metadata:
  name: mongo-catalog
  labels:
    app: mongo
spec:
  ports:
    - port: 27018
      targetPort: 27018
  clusterIP: None  # Headless service
  selector:
    app: mongo