apiVersion: v1
kind: Secret
metadata:
  name: mongo-catalog-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  MONGO_DB: bXliZA== # "mydb"
