apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: app
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: docker.io/alimadany/catalog-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083        
          env: # EVERYTHING BELOW THIS LINE IS WILL BE ADJUSTED
            - name: SPRING_DATA_MONGODB_URI
              value: jdbc:postgresql://postgres-catalog-db.db.svc.cluster.local:5432/mydb
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: global-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083                
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083                 
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
