apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-deployment
  ports:
    - port: 80
      targetPort: 8083            # <-- routes to container’s 8081
