apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8082            # <-- routes to container’s 8081
