apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  type: ClusterIP
  selector:
    app: feedback-deployment
  ports:
    - port: 80
      targetPort: 8082            # <-- routes to container’s 8082
