apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: docker.io/alimadany/apigateway-service:0.1
          ports:
            - containerPort: 9091
          env:
              - name: USER_URI
                value: user-service:8080
              - name: ORDER_URI
                value: order-service:8081
              - name: CATALOG_URI
                value: catalog-service:8082
              - name: FEEDBACK_URI
                value: feedback-service:8083

              
              
              
